container:
  attrs:
    app:
      app_context:
        data:
          yaml:
            class_name: AppContext
            module_path: app.contexts.app
        type: dependency
      base_feature_path:
        data:
          yaml:
            value: app.yml
        type: attribute
      base_path:
        data:
          yaml:
            value: app.yml
        type: attribute
      cli_interface_context:
        data:
          yaml:
            class_name: CliInterfaceContext
            module_path: app.contexts.cli
        type: dependency
      cli_interface_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.cli
        type: dependency
      container_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.container
        type: dependency
      feature_container:
        data:
          yaml:
            class_name: FeatureContainer
            module_path: app.containers.feature
        type: dependency
      feature_context:
        data:
          yaml:
            class_name: FeatureContext
            module_path: app.contexts.feature
        type: dependency
      feature_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.feature
        type: dependency
      error_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.error
        type: dependency
      flag:
        data:
          yaml:
            value: yaml
        type: attribute
      interface_yaml_base_path:
        data:
          yaml:
            value: app.yml
        type: attribute
      error_yaml_base_path:
        data:
          yaml:
            value: app.yml
        type: attribute
    feature:
      add_cli_command:
        data:
          yaml:
            class_name: AddCliCommand
            module_path: app.commands.cli
        type: dependency
      cli_interface_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.cli
        type: dependency
      flag:
        data:
          yaml:
            value: yaml
        type: attribute
      interface_yaml_base_path:
        data:
          yaml:
            value: app.yml
        type: attribute
errors:
  INVALID_REQUEST_DATA:
    message:
      en_US: 'Invalid request contains the following errors: "{}"'
  CLI_INTERFACE_NOT_FOUND:
    message:
      en_US: 'CLI interface with id "{}" not found'
  CLI_COMMAND_ALREADY_EXISTS:
    message:
      en_US: 'CLI command with for feature "{}" already exists'
features:
  groups:
    cli:
      features:
        add_command:
          functions:
          - attribute_id: add_cli_command
            name: Add CLI Command Handler
          name: Add CLI Command
          request_type_path: app.configs.requests.AddCliCommand
interfaces:
  cli:
    commands:
      cli.add_argument:
        arguments:
        - help: cli argument name
          name_or_flags:
          - name
        - help: cli interface id
          name_or_flags:
          - -i
          - --interface-id
          required: true
        - help: feature id
          name_or_flags:
          - --feature-id
          - -f
          required: true
        - help: cli argument description
          name_or_flags:
          - -d
          - --description
          required: true
        - choices:
          - command
          - parent_argument
          default: command
          help: cli argument type
          name_or_flags:
          - --type
        - help: optional cli argument flags
          name_or_flags:
          - --flags
          nargs: +
        - action: store_true
          help: cli argument is required
          name_or_flags:
          - --required
        - help: cli argument default
          name_or_flags:
          - --default
        - action: store_true
          help: cli argument is positional
          name_or_flags:
          - --positional
        - help: cli argument unique action
          name_or_flags:
          - --action
        - help: cli argument value choices
          name_or_flags:
          - --choices
          nargs: +
        - help: available number of cli argument values
          name_or_flags:
          - --nargs
        feature_id: cli.add_argument
        group_id: cli
        name: Add CLI Argument
      cli.add_command:
        arguments:
        - help: cli interface id
          name_or_flags:
          - --interface-id
          - -i
          required: true
        - help: cli command key
          name_or_flags:
          - --command-key
          - -c
          required: true
        - help: context group id
          name_or_flags:
          - --group-id
          - -g
        - help: cli command name
          name_or_flags:
          - name
        - help: cli command description
          name_or_flags:
          - --description
          - -d
        feature_id: cli.add_command
        group_id: cli
        name: Add CLI Command
      cli.add_parent_argument:
        arguments:
        - help: argument action
          name_or_flags:
          - --action
        - help: argument choices
          name_or_flags:
          - --choices
          nargs: +
        - help: argument default
          name_or_flags:
          - --default
        - help: argument flags
          name_or_flags:
          - -f
          - --flags
          nargs: +
        - help: argument description
          name_or_flags:
          - -d
          - --description
          required: true
        - help: argument name
          name_or_flags:
          - name
        - help: available number of arguments
          name_or_flags:
          - --nargs
        - action: store_true
          help: argument is positional
          name_or_flags:
          - -p
          - --positional
        - action: store_true
          help: argument required
          name_or_flags:
          - --required
        - choices:
          - str
          - int
          - float
          - bool
          - list
          - dict
          help: argument type
          name_or_flags:
          - --type
        feature_id: cli.add_parent_argument
        group_id: cli
        name: Add CLI Parent Argument
      object.new:
        feature_id: object.new
        group_id: object
        help: add new model object
        name: Add Object
