container:
  attrs:
    app:
      cli_interface_context:
        type: dependency
        data:
          yaml:
            module_path: app.contexts.cli
            class_name: CliInterfaceContext
      app_context:
        type: dependency
        data:
          yaml:
            module_path: app.contexts.app
            class_name: AppContext
      feature_context:
        type: dependency
        data:
          yaml:
            module_path: app.contexts.feature
            class_name: FeatureContext
      add_cli_command:
        type: dependency
        data:
          yaml:
            module_path: app.commands.cli
            class_name: AddCliCommand
      container_repo:
        type: dependency
        data:
          yaml:
            module_path: app.repositories.container
            class_name: YamlRepository
      cli_interface_repo:
        type: dependency
        data:
          yaml:
            module_path: app.repositories.cli
            class_name: YamlRepository
      feature_repo:
        type: dependency
        data:
          yaml:
            module_path: app.repositories.feature
            class_name: YamlRepository
      base_feature_path:
        type: attribute
        data:
          yaml:
            value: app.yml
      base_path:
        type: attribute
        data:
          yaml:
            value: app.yml
    
errors:
  INVALID_REQUEST_DATA:
    message:
      en_US: 'Invalid request contains the following errors: {}'
features:
  groups:
    cli:
      features:
        add_command:
          request_type_path: app.configs.requests.AddCliCommand
          functions:
          - attribute_id: add_cli_command
            name: Add CLI Command Handler
          name: Add CLI Command
interfaces:
  cli:
    commands:
      cli.add_argument:
        feature_id: cli.add_argument
        group_id: cli
        arguments:
        - help: argument action
          name_or_flags:
          - --action
        - help: argument choices
          name_or_flags:
          - --choices
          nargs: +
        - help: command key
          name_or_flags:
          - -c
          - --command-key
          required: true
        - help: argument default
          name_or_flags:
          - --default
        - help: argument flags
          name_or_flags:
          - -f
          - --flags
          nargs: +
        - help: argument description
          name_or_flags:
          - -d
          - --description
          required: true
        - help: argument name
          name_or_flags:
          - name
        - help: available number of arguments
          name_or_flags:
          - --nargs
        - action: store_true
          help: argument is positional
          name_or_flags:
          - -p
          - --positional
        - action: store_true
          help: argument required
          name_or_flags:
          - --required
        - help: subcommand key
          name_or_flags:
          - -s
          - --subcommand-key
        - choices:
          - str
          - int
          - float
          help: argument type
          name_or_flags:
          - -t
          - --type
        name: Add CLI Argument
      cli.add_command:
        feature_id: cli.add_command
        group_id: cli
        arguments:
        - help: cli command key
          name_or_flags:
          - --command-key
          - -c
          required: true
        - help: context group id
          name_or_flags:
          - --group-id
          - -g
        - help: cli command name
          name_or_flags:
          - name
        - help: cli command description
          name_or_flags:
          - --description
          - -d
        name: Add CLI Command
      cli.add_parent_argument:
        feature_id: cli.add_parent_argument
        group_id: cli
        arguments:
        - help: argument action
          name_or_flags:
          - --action
        - help: argument choices
          name_or_flags:
          - --choices
          nargs: +
        - help: argument default
          name_or_flags:
          - --default
        - help: argument flags
          name_or_flags:
          - -f
          - --flags
          nargs: +
        - help: argument description
          name_or_flags:
          - -d
          - --description
          required: true
        - help: argument name
          name_or_flags:
          - name
        - help: available number of arguments
          name_or_flags:
          - --nargs
        - action: store_true
          help: argument is positional
          name_or_flags:
          - -p
          - --positional
        - action: store_true
          help: argument required
          name_or_flags:
          - --required
        - choices:
          - str
          - int
          - float
          - bool
          - list
          - dict
          help: argument type
          name_or_flags:
          - --type
        name: Add CLI Parent Argument
  

