container:
  attrs:
    app:
      app_context:
        data:
          yaml:
            class_name: AppContext
            module_path: app.contexts.app
        type: dependency
      base_feature_path:
        data:
          yaml:
            value: app.yml
        type: data
      base_path:
        data:
          yaml:
            value: app.yml
        type: data
      cli_interface_context:
        data:
          yaml:
            class_name: CliInterfaceContext
            module_path: app.contexts.cli
        type: dependency
      cli_interface_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.cli
        type: dependency
      container_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.container
        type: dependency
      container_yaml_base_path:
        data:
          yaml:
            value: app.yml
        type: data
      error_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.error
        type: dependency
      error_yaml_base_path:
        data:
          yaml:
            value: app.yml
        type: data
      feature_container:
        data:
          yaml:
            class_name: FeatureContainer
            module_path: app.containers.feature
        type: dependency
      feature_context:
        data:
          yaml:
            class_name: FeatureContext
            module_path: app.contexts.feature
        type: dependency
      feature_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.feature
        type: dependency
      flag:
        data:
          yaml:
            value: yaml
        type: data
      interface_yaml_base_path:
        data:
          yaml:
            value: app.yml
        type: data
    feature:
      add_cli_argument:
        data:
          yaml:
            class_name: AddCliArgument
            module_path: app.commands.cli
        type: dependency
      add_cli_command:
        data:
          yaml:
            class_name: AddCliCommand
            module_path: app.commands.cli
        type: dependency
      add_container_attribute:
        data:
          yaml:
            class_name: AddContainerAttribute
            module_path: app.commands.container
        type: dependency
      add_new_object:
        data:
          yaml:
            class_name: AddNewObject
            module_path: app.commands.object
        type: dependency
      add_object_attribute:
        data:
          yaml:
            class_name: AddObjectAttribute
            module_path: app.commands.object
        type: dependency
      cli_interface_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.cli
        type: dependency
      container_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.container
        type: dependency
      container_yaml_base_path:
        data:
          yaml:
            value: app.yml
        type: data
      flag:
        data:
          yaml:
            value: yaml
        type: data
      interface_yaml_base_path:
        data:
          yaml:
            value: app.yml
        type: data
      object_repo:
        data:
          yaml:
            class_name: YamlRepository
            module_path: app.repositories.object
        type: dependency
      object_yaml_base_path:
        data:
          yaml:
            value: app.yml
        type: data
errors:
  CLI_ARGUMENT_ALREADY_EXISTS:
    message:
      en_US: CLI argument with name or flag "{}" already exists
  CLI_ARGUMENT_INVALID_FEATURE_ID:
    message:
      en_US: Feature ID is required when adding a CLI argument to a command
  CLI_COMMAND_ALREADY_EXISTS:
    message:
      en_US: CLI command with for feature "{}" already exists
  CLI_COMMAND_NOT_FOUND:
    message:
      en_US: CLI command mapped to Feature ID "{}" not found
  CLI_INTERFACE_NOT_FOUND:
    message:
      en_US: CLI interface with id "{}" not found
  CONTAINER_ATTRIBUTE_ALREADY_EXISTS:
    message:
      en_US: Container attribute "{}" already exists within group "{}"
  INVALID_CONTAINER_ATTRIBUTE_DATA:
    message:
      en_US: Container data for attribute with "{}" is invalid
  INVALID_REQUEST_DATA:
    message:
      en_US: 'Invalid request contains the following errors: "{}"'
  OBJECT_ALREADY_EXISTS:
    message:
      en_US: Object with class name "{}" already exists
  OBJECT_NOT_FOUND:
    message:
      en_US: Object with id "{}" not found
features:
  groups:
    cli:
      features:
        add_argument:
          functions:
          - attribute_id: add_cli_argument
            name: Add CLI Argument Handler
          name: Add CLI Argument
          request_type_path: app.configs.requests.AddCliArgument
        add_command:
          functions:
          - attribute_id: add_cli_command
            name: Add CLI Command Handler
          name: Add CLI Command
          request_type_path: app.configs.requests.AddCliCommand
    container:
      features:
        add_attribute:
          functions:
          - attribute_id: add_container_attribute
            name: Add Container Attribute Handler
          name: Add Container Attribute
          request_type_path: app.configs.requests.AddContainerAttribute
    object:
      features:
        add_attribute:
          functions:
          - attribute_id: add_object_attribute
            name: Add Object Attribute Handler
          name: Add Object Attribute
          request_type_path: app.configs.requests.AddObjectAttribute
        new:
          functions:
          - attribute_id: add_new_object
            name: Add New Object Handler
          name: Add New Object
          request_type_path: app.configs.requests.AddNewObject
interfaces:
  cli:
    commands:
      cli.add_argument:
        arguments:
        - help: cli argument name
          name_or_flags:
          - name
          type: str
        - help: cli interface id
          name_or_flags:
          - -i
          - --interface-id
          required: true
          type: str
        - help: feature id
          name_or_flags:
          - --feature-id
          - -f
          required: true
          type: str
        - help: cli argument description
          name_or_flags:
          - -d
          - --description
          required: true
          type: str
        - choices:
          - command
          - parent_argument
          default: command
          help: cli argument type
          name_or_flags:
          - --arg-type
          type: str
        - choices:
          - str
          - int
          - float
          default: str
          help: cli argument data type
          name_or_flags:
          - --type
          type: str
        - help: optional cli argument flags
          name_or_flags:
          - --flags
          nargs: +
          type: str
        - action: store_true
          help: cli argument is required
          name_or_flags:
          - --required
          type: str
        - help: cli argument default
          name_or_flags:
          - --default
          type: str
        - action: store_true
          help: cli argument is positional
          name_or_flags:
          - --positional
          type: str
        - help: cli argument unique action
          name_or_flags:
          - --action
          type: str
        - help: cli argument value choices
          name_or_flags:
          - --choices
          nargs: +
          type: str
        - help: available number of cli argument values
          name_or_flags:
          - --nargs
          type: str
        feature_id: cli.add_argument
        group_id: cli
        name: Add CLI Argument
      cli.add_command:
        arguments:
        - help: cli interface id
          name_or_flags:
          - --interface-id
          - -i
          required: true
          type: str
        - help: cli command key
          name_or_flags:
          - --command-key
          - -c
          required: true
          type: str
        - help: context group id
          name_or_flags:
          - --group-id
          - -g
          type: str
        - help: cli command name
          name_or_flags:
          - name
          type: str
        - help: cli command description
          name_or_flags:
          - --description
          - -d
          type: str
        feature_id: cli.add_command
        group_id: cli
        name: Add CLI Command
      container.set_attribute:
        arguments:
        - help: attribute container id
          name_or_flags:
          - id
          type: str
        - help: attribute container context group id
          name_or_flags:
          - --group-id
          - -g
          required: true
          type: str
        - choices:
          - attribute
          - dependency
          help: attribute container type
          name_or_flags:
          - --type
          - -t
          required: true
          type: str
        - help: container attribute infrastructure flag
          name_or_flags:
          - --flag
          - -f
          required: true
          type: str
        - help: container attribute data (separated by '=')
          name_or_flags:
          - --data
          nargs: +
          required: true
          type: str
        feature_id: container.add_attribute
        group_id: container
        help: set container attribute
        name: Set Container Attribute
      object.add_attribute:
        arguments:
        - help: object attribute name
          name_or_flags:
          - name
          type: str
        - help: object attribute parent object id
          name_or_flags:
          - --object-id
          - -o
          required: true
          type: str
        - help: object attribute description
          name_or_flags:
          - --description
          - -d
          required: true
          type: str
        - choices:
          - str
          - int
          - float
          - bool
          - date
          - datetime
          - list
          - dict
          - model
          - poly
          help: object attribute data type
          name_or_flags:
          - --type
          - -t
          required: true
          type: str
        - choices:
          - str
          - int
          - float
          - bool
          - date
          - datetime
          - model
          help: object attribute inner data type (list/dict)
          name_or_flags:
          - --inner-type
          type: str
        - help: object id for object attribute model type
          name_or_flags:
          - --type-object-id
          type: str
        - help: object ids for object attribute poly type
          name_or_flags:
          - --poly-type-object-ids
          nargs: +
          type: str
        - action: store_true
          help: true if the object attribute value is required
          name_or_flags:
          - --required
          type: str
        - help: object attribute default value
          name_or_flags:
          - --default
          type: str
        - help: set of valid object attribute values
          name_or_flags:
          - --choices
          type: str
        - help: object attribute type settings (separated by '=')
          name_or_flags:
          - --type-settings
          nargs: +
          type: str
        feature_id: object.add_attribute
        group_id: object
        help: add attribute to model object
        name: Add Object Attribute
      object.new:
        arguments:
        - help: model object name
          name_or_flags:
          - name
          type: str
        - help: id of model object context group
          name_or_flags:
          - --group-id
          - -g
          required: true
          type: str
        - choices:
          - entity
          - value_object
          help: model object type
          name_or_flags:
          - --type
          - -t
          required: true
          type: str
        - help: model object printed class name
          name_or_flags:
          - --class-name
          - -c
          required: true
          type: str
        - help: model object description
          name_or_flags:
          - --description
          - -d
          required: true
          type: str
        - help: id of model object base type
          name_or_flags:
          - --base-type-id
          type: str
        feature_id: object.new
        group_id: object
        help: add new model object
        name: Add Object
objects:
  date_settings:
    base_type_id: object_type_settings
    class_name: DateSettings
    description: Type-specific settings for an date object attribute.
    group_id: object
    name: Date Settings
    type: value_object
  date_time_settings:
    base_type_id: object_type_settings
    class_name: DateTimeSettings
    description: Type-specific settings for a datetime object attribute.
    group_id: object
    name: Date Time Settings
    type: value_object
  dict_settings:
    base_type_id: object_type_settings
    class_name: DictSettings
    description: Type-specific settings for a dict object attribute.
    group_id: object
    name: Dict Settings
    type: value_object
  list_settings:
    base_type_id: object_type_settings
    class_name: ListSettings
    description: Type-specific settings for a list object attribute.
    group_id: object
    name: List Settings
    type: value_object
  model_attribute:
    class_name: ModelAttribute
    description: An attribute of a model object.
    group_id: object
    name: Model Attribute
    type: value_object
  model_object:
    class_name: ModelObject
    description: A domain model component defined as a class object.
    group_id: object
    name: Model Object
    type: entity
  object_type_settings:
    class_name: ObjectTypeSettings
    description: Type-specific settings for an object attribute.
    group_id: object
    name: Object Type Settings
    type: value_object
  string_settings:
    base_type_id: object_type_settings
    class_name: StringSettings
    description: Type-specific settings for an string attribute.
    group_id: object
    name: String Settings
    type: value_object
